# Site settings
title: Nkore Drum
description: >- # this means to ignore newlines until "baseurl:"
  A digital storytelling blog documenting the rich culture, stories, and development of Western Uganda.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # will be set by Netlify

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - netlify-cms-app

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .gitignore
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - .idea
  - .vscode
  - __pycache__
  - .forestry
  - netlify.toml
  - admin/index.html

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .gitignore
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - .idea
  - .vscode
  - __pycache__
