[build]
  base = "/"
  publish = "/_site"
  command = "bundle exec jekyll build"

[build.environment]
  JEKYLL_ENV = "production"
  JEKYLL_GITHUB_TOKEN = "${JEKYLL_GITHUB_TOKEN}"

[context.production]
  command = "bundle exec jekyll build"

[context.deploy-preview]
  command = "bundle exec jekyll build"

[context.split-testing]
  command = "bundle exec jekyll build"
