[build]
  base = "/"
  publish = "/_site"
  command = "pwsh -File build.ps1"
  functions = "netlify/functions"

[build.environment]
  JEKYLL_ENV = "production"
  JEKYLL_GITHUB_TOKEN = "${JEKYLL_GITHUB_TOKEN}"

[context.production]
  command = "pwsh -File build.ps1"

[context.deploy-preview]
  command = "pwsh -File build.ps1"

[context.split-testing]
  command = "pwsh -File build.ps1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
