[build]
  command = "bundle exec jekyll build"
  publish = "_site"
  base = ""

[context.production.environment]
  JEKYLL_ENV = "production"

[context.deploy-preview.environment]
  JEKYLL_ENV = "development"

[context.split-testing.environment]
  JEKYLL_ENV = "development"
